export const availableLocations = [
  {
    district: "Thiruvananthapuram",
    cities: ["Thiruvananthapuram", "Neyyattinkara", "Varkala", "Attingal"],
  },
  {
    district: "Kollam",
    cities: ["Kollam", "Karunagappally", "Punalur", "Paravur"],
  },
  {
    district: "Pathanamthitta",
    cities: ["Pathanamthitta", "Adoor", "Thiruvalla", "Pandalam"],
  },
  {
    district: "Alappuzha",
    cities: ["Alappuzha", "Cherthala", "Kayamkulam", "Haripad"],
  },
  {
    district: "Kottayam",
    cities: ["Kottayam", "Changanassery", "Pala", "Ettumanoor"],
  },
  {
    district: "Idukki",
    cities: ["Thodupuzha", "Munnar", "Kattappana", "Nedumkandam"],
  },
  {
    district: "Ernakulam",
    cities: ["Kochi", "Aluva", "Perumbavoor", "Kothamangalam"],
  },
  {
    district: "Thrissur",
    cities: ["Thrissur", "Guruvayur", "Chalakudy", "Kodungallur"],
  },
  {
    district: "Palakkad",
    cities: ["Palakkad", "Ottappalam", "Mannarkkad", "Shoranur"],
  },
  {
    district: "Malappuram",
    cities: ["Malappuram", "Manjeri", "Tirur", "Perinthalmanna"],
  },
  {
    district: "Kozhikode",
    cities: ["Kozhikode", "Vadakara", "Koyilandy", "Ramanattukara"],
  },
  {
    district: "Wayanad",
    cities: ["Kalpetta", "Sulthan Bathery", "Mananthavady"],
  },
  {
    district: "Kannur",
    cities: ["Kannur", "Thalassery", "Payyannur", "Taliparamba"],
  },
  {
    district: "Kasaragod",
    cities: ["Kasaragod", "Kanhangad", "Uppala"],
  },
];

export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const amenities = [
  "Swimming Pool",
  "Spa",
  "Gym",
  "Free WiFi",
  "Air Conditioning",
  "Restaurant",
  "Bar",
  "Room Service",
  "24 Hour Front Desk",
  "Parking",
  "Free Parking",
  "Airport Shuttle",
  "Family Rooms",
  "Non Smoking Rooms",
  "Breakfast Included",
  "Laundry Service",
  "Dry Cleaning",
  "Housekeeping",
  "Business Center",
  "Meeting Rooms",
  "Conference Hall",
  "Elevator",
  "Wheelchair Accessible",
  "Pet Friendly",
  "Garden",
  "Terrace",
  "Beach Access",
  "Private Beach",
  "Kids Play Area",
  "Kids Pool",
  "Babysitting",
  "BBQ Facilities",
  "Kitchen",
  "Kitchenette",
  "Refrigerator",
  "Microwave",
  "Coffee Maker",
  "Smart TV",
  "Cable TV",
  "Streaming Services",
  "Hot Tub",
  "Sauna",
  "Yoga Room",
  "Fitness Classes",
  "Game Room",
  "Library",
  "Bicycle Rental",
  "Car Rental",
  "EV Charging Station",
  "Security 24/7",
  "CCTV",
  "Fire Safety System",
  "First Aid",
  "Luggage Storage",
  "Currency Exchange",
  "Tour Desk",
  "Concierge",
  "Soundproof Rooms",
  "Balcony",
  "Sea View",
  "Mountain View",
  "City View",
];
